name: "auditor-action"
description: "The Auditor"
author: "Grant Birkinbine"

inputs:
  config:
    description: The path to the auditor's config file
    default: auditor.yml
    required: true
  json_diff_path:
    description: The path to the json diff file
    default: git-diff-action-output.json
    required: true
  annotate_pr:
    description: Annotate the PR with the audit results
    default: "false"
    required: true

branding:
  icon: "lock"
  color: "gray-dark"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@v2.6.0
      id: git-diff-action
      with:
        json_diff_file_output: ${{ inputs.json_diff_path }}
        base_branch: HEAD^1 # compare the PR merge commit against its first parent
        file_output_only: "true" # do not print any diff output to the console (safety first)
        search_path: '.' # look in the entire repo for changes
        max_buffer_size: "10000000" # the default git diff buffer size, increase if you have issues

    - name: auditor-action
      uses: GrantBirki/auditor-action-core@v2.3.0
      with:
        annotate_pr: ${{ inputs.annotate_pr }}
      env:
        CONFIG_PATH: ${{ inputs.config }}
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}

    - name: cleanup
      env:
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}
      run: rm $JSON_DIFF_PATH
      shell: bash
