name: "auditor-action"
description: "The Auditor"
author: "Grant Birkinbine"

inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client - Provided
      for you by default! If you are using annotations on pull requests, you may
      need to use a GitHub App token with checks:write permissions instead'
    default: ${{ github.token }}
    required: true
  config:
    description: The path to the auditor's config file
    default: config/auditor.yml
    required: true
  json_diff_path:
    description: The path to the json diff file
    default: diff.json
    required: true
  github_base_url:
    description: 'The base URL for the GitHub instance you are using'
    default: 'https://github.com'
    required: true
  annotate_pr:
    description: Annotate the PR with the audit results
    default: "true"
    required: true
  annotate_name:
    description: 'The name of the annotation to name to use'
    default: 'The Auditor'
    required: true
  annotate_title:
    description: 'The title of the annotation to use'
    default: 'The Auditor has detected findings in your pull request'
    required: true
  annotate_summary:
    description: 'The summary of the annotation to use'
    default: 'Please review the findings and make any necessary changes'
    required: true
  annotate_status:
    description: 'The status of the annotation to use'
    default: 'completed'
    required: true

branding:
  icon: "lock"
  color: "gray-dark"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@f9084974667db3cecc39baa7d09f0c95656f77b2 # pin@v2.6.0
      id: git-diff-action
      with:
        json_diff_file_output: ${{ inputs.json_diff_path }}
        base_branch: HEAD^1 # compare the PR merge commit against its first parent
        file_output_only: "true" # do not print any diff output to the console (safety first)
        search_path: '.' # look in the entire repo for changes
        max_buffer_size: "10000000" # the default git diff buffer size, increase if you have issues

    - name: auditor-action
      uses: GrantBirki/auditor-action-core@a5bc8211a5aeda51a3bba4baa858628d0941ad25 # pin@v3.0.0
      with:
        github_token: ${{ inputs.github_token }}
        annotate_pr: ${{ inputs.annotate_pr }}
        config_path: ${{ inputs.config }}
        json_diff_path: ${{ inputs.json_diff_path }}
        github_base_url: ${{ inputs.github_base_url }}
        annotate_name: ${{ inputs.annotate_name }}
        annotate_title: ${{ inputs.annotate_title }}
        annotate_summary: ${{ inputs.annotate_summary }}
        annotate_status: ${{ inputs.annotate_status }}

    - name: cleanup
      env:
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}
      run: rm $JSON_DIFF_PATH
      shell: bash
