name: "auditor-action"
description: "The Auditor"
author: "Grant Birkinbine"

inputs:
  config:
    description: The path to the auditor's config file
    default: auditor.yml
    required: true
  json_diff_path:
    description: The path to the json diff file
    default: git-diff-action-output.json
    required: true

branding:
  icon: "lock"
  color: "gray-dark"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@v2.0.1
      id: git-diff-action
      with:
        json_diff_file_output: ${{ inputs.json_diff_path }}

    - name: auditor-action
      uses: GrantBirki/auditor-action-core@v2.0.4
      env:
        CONFIG_PATH: ${{ inputs.config }}
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}

    - name: cleanup
      env:
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}
      run: rm $JSON_DIFF_PATH
      shell: bash
