name: "auditor-action"
description: "The Auditor"
author: "Grant Birkinbine"

inputs:
  github_token:
    description: 'The GitHub token used to create an authenticated client - Provided
      for you by default! If you are using annotations on pull requests, you may
      need to use a GitHub App token with checks:write permissions instead'
    default: ${{ github.token }}
    required: true
  config:
    description: The path to the auditor's config file
    default: config/auditor.yml
    required: true
  json_diff_path:
    description: The path to the json diff file
    default: diff.json
    required: true
  github_base_url:
    description: 'The base URL for the GitHub instance you are using'
    default: 'https://github.com'
    required: true
  annotate_pr:
    description: Annotate the PR with the audit results
    default: "true"
    required: true
  annotate_name:
    description: 'The name of the annotation to name to use'
    default: 'The Auditor'
    required: true
  annotate_title:
    description: 'The title of the annotation to use'
    default: 'The Auditor has detected findings in your pull request'
    required: true
  annotate_summary:
    description: 'The summary of the annotation to use'
    default: 'Please review the findings and make any necessary changes'
    required: true
  annotate_status:
    description: 'The status of the annotation to use'
    default: 'completed'
    required: true
  write_results_path:
    description: 'The path to write the markdown results to (for custom reporting) -
      Leave unset to disable writing results to a file'
    default: ''
    required: true
  # git diff action specific below
  base_branch:
    description: 'The base branch to compare the PR against'
    default: HEAD^1 # compare the PR merge commit against its first parent
    required: true
  file_output_only:
    description: 'Only output the diff to the json file'
    default: "true" # do not print any diff output to the console (safety first)
    required: true
  search_path:
    description: 'The path to search for changes'
    default: '.' # look in the entire repo for changes
    required: true
  max_buffer_size:
    description: 'The maximum buffer size for the git diff command'
    default: "10000000" # the default git diff buffer size, increase if you have issues
    required: true

branding:
  icon: "lock"
  color: "gray-dark"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@f65a78c343ee50737aebbe653e35f3067752c7b3 # pin@v2.8.0
      id: git-diff-action
      with:
        json_diff_file_output: ${{ inputs.json_diff_path }}
        base_branch: ${{ inputs.base_branch }}
        file_output_only: ${{ inputs.file_output_only }}
        search_path: ${{ inputs.search_path }}
        max_buffer_size: ${{ inputs.max_buffer_size }}

    - name: auditor-action
      uses: GrantBirki/auditor-action-core@615b23cdfd7a938565863678e6b31d083267b2b9 # pin@v3.3.1
      with:
        github_token: ${{ inputs.github_token }}
        annotate_pr: ${{ inputs.annotate_pr }}
        config_path: ${{ inputs.config }}
        json_diff_path: ${{ inputs.json_diff_path }}
        github_base_url: ${{ inputs.github_base_url }}
        annotate_name: ${{ inputs.annotate_name }}
        annotate_title: ${{ inputs.annotate_title }}
        annotate_summary: ${{ inputs.annotate_summary }}
        annotate_status: ${{ inputs.annotate_status }}
        write_results_path: $ {{ inputs.write_results_path }}

    - name: cleanup
      env:
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}
      run: rm $JSON_DIFF_PATH
      shell: bash
