name: "auditor-action"
description: "The Auditor"
author: "Grant Birkinbine"

inputs:
  config:
    description: The path to the auditor's config file
    default: auditor.yml
    required: true
  json_diff_path:
    description: The path to the json diff file
    default: git-diff-action-output.json
    required: true

branding:
  icon: "lock"
  color: "gray-dark"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@b4b60819c4e5d05f420f600e6497cd7a4f96d53f # pin@v2.4.0
      id: git-diff-action
      with:
        json_diff_file_output: ${{ inputs.json_diff_path }}
        base_branch: HEAD^1 # compare the PR merge commit against its first parent
        file_output_only: "true" # do not print any diff output to the console (safety first)
        search_path: '.' # look in the entire repo for changes
        max_buffer_size: "1000000" # the default git diff buffer size, increase if you have issues

    - name: auditor-action
      uses: GrantBirki/auditor-action-core@d20693663049b7fee4a0f6e2b3123643e2e8941e # pin@v2.2.0
      env:
        CONFIG_PATH: ${{ inputs.config }}
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}

    - name: cleanup
      env:
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}
      run: rm $JSON_DIFF_PATH
      shell: bash
