name: "auditor-action"
description: "The Auditor"
author: "Grant Birkinbine"

inputs:
  config:
    description: The path to the auditor's config file
    default: auditor.yml
    required: true
  json_diff_path:
    description: The path to the json diff file
    default: git-diff-action-output.json
    required: true

branding:
  icon: "lock"
  color: "gray-dark"

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin@v3.0.2
      with:
        fetch-depth: 0 # needed to checkout all branches

    - name: git-diff-action
      uses: GrantBirki/git-diff-action@6598b319b117b1f20daad8a7619bec674fa9a549 # pin@v1.1.0
      id: git-diff-action
      with:
        json_diff_file_output: ${{ inputs.json_diff_path }}

    - name: auditor-action
      uses: GrantBirki/auditor-action-core@c44088ef2b60dbb91ebfc20902148d48c025622e # pin@v2.0.3
      env:
        CONFIG_PATH: ${{ inputs.config }}
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}

    - name: cleanup
      env:
        JSON_DIFF_PATH: ${{ inputs.json_diff_path }}
      run: rm $JSON_DIFF_PATH
      shell: bash
